version: "2.1"

services:
  ledger:
    image: bat-ledger
    build: .
    restart: always
    environment:
      - "MONGODB_URI=${MONGODB_URI-mongodb://mongo}"
      - "NODE_ENV=${NODE_ENV-development}"
      - "REDIS_URL=${REDIS_URL-redis://redis:6379}"
      - "BAT_LEDGER_SERVER=${BAT_LEDGER_SERVER-http://ledger-web:3001}"
      - "BAT_EYESHADE_SERVER=${BAT_EYESHADE_SERVER-http://eyeshade-web:3002}"
      - "BAT_HELPER_SERVER=${BAT_HELPER_SERVER-http://helper-web:3004}"
      - "BAT_GRANT_SERVER=${BAT_GRANT_SERVER-http://grant-web:3333}"
      - BALANCE_CACHE_TTL_S
      - BALANCE_TOKEN
      - BALANCE_URL
      - BAT_SETTLEMENT_ADDRESS
      - BITCOIN_AVERAGE_PUBLIC_KEY
      - BITCOIN_AVERAGE_SECRET_KEY
      - COINBASE_WIDGET_CODE
      - DEBUG
      - EYESHADE_GITHUB_CLIENT_ID
      - EYESHADE_GITHUB_CLIENT_SECRET
      - EYESHADE_SLACK_CHANNEL
      - EYESHADE_SLACK_ICON_URL
      - FIXIE_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_BYE
      - GITHUB_LOGIN_WORLD
      - GITHUB_ORG
      - LEDGER_GITHUB_CLIENT_ID
      - LEDGER_GITHUB_CLIENT_SECRET
      - LEDGER_SLACK_CHANNEL
      - LEDGER_SLACK_ICON_URL
      - LEDGER_URL
      - PORT
      - PUBLISHERS_TOKEN
      - PUBLISHERS_URL
      - REDEEMER_CARD_ID
      - REDEEMER_TOKEN
      - REDEEMER_URL
      - SENTRY_DSN
      - SLACK_CHANNEL
      - SLACK_ICON_URL
      - SLACK_WEBHOOK
      - TESTING_COHORTS
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
      - UPHOLD_CLIENT_ID
      - UPHOLD_CLIENT_SECRET
      - UPHOLD_DONOR_CARD_ID
      - UPHOLD_ENVIRONMENT
      - VOTING_COHORTS
